### ISSUE TITLE
Wrong wish 

### ISSUE THREAD

**Issue by PriyansuMaurya** [VishwaGauravIn/summerx#8]
I am viewing the website in the afternoon but it is showing "Good morning, Priyanshu". So adding code that would change the wish according to the time would be incredible.

![image](https://user-images.githubusercontent.com/101447544/206199815-0bebb645-e34f-4bc9-96dc-a22f87a0a366.png)

**Comment by VishwaGauravIn** [comment]
I have set it be according to the timing, If you will visit the site from 12pm to 4pm, you will see good afternoon. If the problem still exists, please share the timing and check your system time.
![image](https://user-images.githubusercontent.com/81325730/206230489-91f9993e-f001-464a-9fc8-1becb0775e25.png)
